"""
Direction-consistency post-check.

Implements the **post-hoc consistency-check** step described at the end
of Sec. 3.2 (Step 3) and in App. A.3 of the paper. After every
Detailed Movement Instruction has been generated by ``detailed_movement``,
we run an independent text-only LLM call that:

  1. parses the segment's *direction descriptor* (e.g.
     ``"left-forward"``) into a per-axis label (forward/backward,
     left/right, up/down);
  2. parses the free-text ``move_type`` written by the VLM into the same
     per-axis labels;
  3. compares the two and emits a structured JSON record indicating
     whether they agree.

NCSs whose two labels disagree on any axis are subsequently dropped from
the Detailed Movement Instruction pool (filtering happens downstream;
this module *only* writes the check result back into each segment's
``sub_traj_label.direction_consist_post_check`` field).

The module is purely text-based: it does **not** load any video frames.
The default model is the same ``Qwen3.5-27B`` used for instruction
annotation, served via ``vllm`` with ``apply_chat_template(...,
enable_thinking=False)`` for fast deterministic JSON output. The prompt
template is at ``./prompts/direction_consistency.txt``.
"""

from __future__ import annotations

import json
import os
import random
from pathlib import Path
from typing import Dict, List, Optional

# NOTE: torch / transformers / vllm are imported lazily.

from .detailed_movement import (
    _prepare_inputs_for_vllm,
    parse_model_output,
)

DEFAULT_PROMPT_PATH = Path(__file__).parent / "prompts" / "direction_consistency.txt"
DEFAULT_MODEL_PATH = "Qwen/Qwen3.5-27B"
DEFAULT_OUTPUT_KEY = "direction_consist_post_check"


class DirectionConsistencyChecker:
    """vLLM-served text-only consistency checker.

    Args:
        model_path:        HuggingFace Hub id or local path to the LLM.
        prompt_path:       Prompt template; expects two placeholders,
                           ``{{DIRECTION_DESCRIPTION}}`` and ``{{MOVE_TYPE}}``.
        gpu_nums:          Tensor-parallel size.
        gpu_memory_util:   vLLM ``gpu_memory_utilization`` knob.
        max_model_len:     Context window; 32k is plenty for this short task.
        enable_thinking:   Whether to keep Qwen3.5 thinking mode on.
    """

    def __init__(
        self,
        model_path: str = DEFAULT_MODEL_PATH,
        prompt_path: Optional[str] = None,
        *,
        gpu_nums: int = 1,
        gpu_memory_util: float = 0.85,
        max_model_len: int = 32768,
        enable_thinking: bool = False,
    ) -> None:
        from transformers import AutoProcessor   # lazy
        from vllm import LLM, SamplingParams     # lazy

        os.environ.setdefault("VLLM_WORKER_MULTIPROC_METHOD", "spawn")

        self.model_path = model_path
        self.enable_thinking = enable_thinking

        seed = random.randint(0, 10_000)
        self.model = LLM(
            model=self.model_path,
            trust_remote_code=True,
            gpu_memory_utilization=gpu_memory_util,
            enforce_eager=False,
            tensor_parallel_size=gpu_nums,
            seed=seed,
            max_model_len=max_model_len,
        )

        # Determinism is desirable for a verification task; temperature=0.
        self.sampling_params = SamplingParams(
            temperature=0,
            top_k=-1,
            max_tokens=512,
            stop_token_ids=[],
        )

        self.processor = AutoProcessor.from_pretrained(self.model_path)

        prompt_path = Path(prompt_path) if prompt_path else DEFAULT_PROMPT_PATH
        with prompt_path.open("r", encoding="utf-8") as f:
            self.prompt_template = f.read()
        self.prompt_path = str(prompt_path)

    # -----------------------------------------------------------------------

    def check_batch(self, items: List[Dict]) -> List[Optional[Dict]]:
        """Run a batch of consistency checks.

        Args:
            items: List of ``{"direction_description": str, "move_type": str}``.

        Returns:
            List of parsed JSON records (or ``None`` on parse failure).
            Each record carries an ``is_consistent`` boolean plus a short
            justification (see ``./prompts/direction_consistency.txt``).
        """
        all_inputs = []
        for it in items:
            text = self.prompt_template.replace(
                "{{DIRECTION_DESCRIPTION}}", it["direction_description"],
            ).replace(
                "{{MOVE_TYPE}}", it["move_type"],
            )
            messages = [{"role": "user", "content": [{"type": "text", "text": text}]}]
            all_inputs.append(_prepare_inputs_for_vllm(
                messages, self.processor, enable_thinking=self.enable_thinking,
            ))
        outputs = self.model.generate(all_inputs, sampling_params=self.sampling_params)
        return [parse_model_output(o.outputs[0].text) for o in outputs]

    def check_single(self, direction_description: str, move_type: str) -> Optional[Dict]:
        return self.check_batch([{
            "direction_description": direction_description,
            "move_type": move_type,
        }])[0]


# ---------------------------------------------------------------------------
# Per-file driver
# ---------------------------------------------------------------------------

def _segment_needs_check(seg: Dict, *, output_key: str) -> bool:
    sub = seg.get("sub_traj_label")
    if not isinstance(sub, dict):
        return False
    if sub.get("annotatable") is not True:
        return False
    if not sub.get("move_type"):
        return False
    if not seg.get("direction_description"):
        return False
    if output_key in sub:
        return False
    return True


def check_consistency_for_file(
    json_path: str,
    checker: DirectionConsistencyChecker,
    *,
    output_key: str = DEFAULT_OUTPUT_KEY,
) -> bool:
    """Run direction-consistency check for every eligible segment in a
    sample JSON file. Mutates the JSON in place. Returns ``True`` if any
    segment was updated.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    seg_list = data.get("segments", {}).get("segment_list", [])
    if not seg_list:
        return False

    items, indices = [], []
    for idx, seg in enumerate(seg_list):
        if _segment_needs_check(seg, output_key=output_key):
            items.append({
                "direction_description": seg["direction_description"],
                "move_type": seg["sub_traj_label"]["move_type"],
            })
            indices.append(idx)
    if not items:
        return False

    results = checker.check_batch(items)
    updated = False
    for seg_idx, res in zip(indices, results):
        sub = seg_list[seg_idx]["sub_traj_label"]
        if isinstance(res, dict) and "is_consistent" in res:
            sub[output_key] = res
        else:
            sub[output_key] = {"parse_success": False, "raw_result": res}
        updated = True

    if updated:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
    return updated


def _cli() -> None:
    import argparse

    p = argparse.ArgumentParser(
        description=(
            "Direction-consistency post-check (text-only). Updates each "
            "labeled JSON in-place under sub_traj_label.<output_key>."
        ),
    )
    p.add_argument("--input_dir", required=True)
    p.add_argument("--model_path", default=DEFAULT_MODEL_PATH)
    p.add_argument("--prompt_path", default=str(DEFAULT_PROMPT_PATH))
    p.add_argument("--gpu_nums", type=int, default=1)
    p.add_argument("--output_key", default=DEFAULT_OUTPUT_KEY)
    p.add_argument("--chunk_id", type=int, default=-1)
    p.add_argument("--chunk_nums", type=int, default=1)
    args = p.parse_args()

    files = sorted(f for f in os.listdir(args.input_dir) if f.endswith(".json"))
    if args.chunk_id >= 0:
        per = len(files) // max(1, args.chunk_nums)
        s = args.chunk_id * per
        e = len(files) if args.chunk_id == args.chunk_nums - 1 else (args.chunk_id + 1) * per
        files = files[s:e]

    checker = DirectionConsistencyChecker(
        model_path=args.model_path,
        prompt_path=args.prompt_path,
        gpu_nums=args.gpu_nums,
    )

    processed, skipped, errors = 0, 0, 0
    for fname in files:
        path = os.path.join(args.input_dir, fname)
        try:
            if check_consistency_for_file(path, checker, output_key=args.output_key):
                processed += 1
            else:
                skipped += 1
        except Exception as exc:  # noqa: BLE001
            errors += 1
            print(f"  [error] {fname}: {exc}")
    print(f"[done] processed={processed}, skipped={skipped}, errors={errors}")


if __name__ == "__main__":
    _cli()
